version : "3.8"
services:
  nginx:
    image: nginx:1.22.0-alpine
    ports: 
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/public:/usr/src/app
    restart: on-failure

  php: 
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/usr/src/app:rw
      - ./env:/usr/src/env
    restart: on-failure
    user: 1000:1000
    env_file:
      - ./env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rssTranslator
    restart: on-failure
