version: "3.8"

services:
    nginx:
        image: nginx:1.22.0-alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app/public:/usr/src/app:ro
        restart: on-failure

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
            # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://localhost
        # Comment the following line to disable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev
        volumes:
            - mercure_data:/data
            - mercure_config:/config

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./app:/usr/src/app:rw
            - ./.env:/usr/src/app/.env:rw
        restart: on-failure
        user: 1000:1000
        env_file:
            - ./.env
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0.29
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        restart: on-failure
        volumes:
            - mysql_data:/var/lib/mysql

    scheduler:
        build:
            dockerfile: docker/php/Dockerfile
            target: php-scheduler
            context: .
        environment:
            - TZ
        env_file:
            - .env
        restart: always
        volumes:
            - ./app:/usr/src/app:rw
            - ./.env:/usr/src/app/.env:ro
    adminer:
        image: adminer
        restart: on-failure
        ports:
            - "8080:8080"

volumes:
    mysql_data: ~
    mercure_data:
    mercure_config:
