version: "3.8"
services:
    nginx:
        image: nginx:1.22.0-alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./app/public:/usr/src/app:ro
        restart: on-failure

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./app:/usr/src/app:rw
            - ./.env:/usr/src/app/.env:ro
        restart: on-failure
        user: 1000:1000
        env_file:
            - ./.env
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0.29
        environment:
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_ROOT_PASSWORD
        restart: on-failure
        volumes:
            - mysql_data:/var/lib/mysql

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - "8080:8080"

    runner:
        build:
            context: .
            dockerfile: ./docker/runner/Dockerfile
        environment:
            - GITHUB_REPOSITORY_URL
            - GITHUB_TOKEN
volumes:
    mysql_data: ~
