homepage:
    path: /
    controller: Application\Controller\HomepageController
    methods: GET

publish_mercure:
    path: /publish
    controller: Application\Controller\PublishController
    methods: GET
