imports:
    - { resource: parameters.yaml }
    - { resource: services/ }

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    App\Domain\TranslatorInterface:
        class: App\Application\DeeplTranslator
        arguments:
            $apiKey: '%deeplApiKey%'
            $targetLanguage: '%deeplTargetLanguage%'
            $domainUrl: '%deeplDomainUrl%'

    App\Application\LivesquawkClient:
        arguments:
            $livesquawkUrl: '%livesquawkUrl%'
            $livesquawkAuthKey: '%livesquawkAuthKey%'

    App\Domain\NewsfeedProviderInterface:
        class: App\Application\LivesquawkNewsfeedProvider
