imports:
    - { resource: parameters.yaml }
    - { resource: services/ }

services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'
            - '../src/Domain/'
            - '../src/Application/'
            - '../src/Infrastructure/'

    Application\:
        resource: "../src/Application/"

    Domain\TranslatorInterface:
        class: Application\DeeplTranslator
        arguments:
            $apiKey: '%deeplApiKey%'
            $targetLanguage: '%deeplTargetLanguage%'
            $domainUrl: '%deeplDomainUrl%'

    Application\LivesquawkClient:
        arguments:
            $livesquawkUrl: '%livesquawkUrl%'
            $livesquawkAuthKey: '%livesquawkAuthKey%'

    Domain\NewsfeedProviderInterface:
        class: Application\LivesquawkNewsfeedProvider

    Domain\Repository\Newsfeeds:
        alias: Infrastructure\Doctrine\Repository\Newsfeeds
