services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Infrastructure\Doctrine\Repository\:
        resource: "../../src/Infrastructure/Doctrine/Repository/*"

    Domain\Repository\Newsfeeds:
        class: Infrastructure\Doctrine\Repository\Newsfeeds
